requires 'Carp';
requires 'Feature::Compat::Class';
requires 'File::Find::Rule';
requires 'File::Find::Rule::Perl';
requires 'File::Path';
requires 'Git::Repository';
requires 'Module::Pluggable';
requires 'Moose';
requires 'Moose::Util::TypeConstraints';
requires 'MooseX::MarkAsMethods';
requires 'MooseX::NonMoose';
requires 'Path::Tiny';
requires 'Template';
requires 'Test::Exception';
requires 'Test::LWP::UserAgent';
requires 'Test::More';
requires 'URI';

test_requires 'LWP';
