
DROP TABLE IF EXISTS repo;
DROP TABLE IF EXISTS file;
DROP TABLE IF EXISTS run;
DROP TABLE IF EXISTS run_file;

CREATE TABLE repo (
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
name CHAR(50) NOT NULL,
uri VARCHAR(500) NOT NULL,
owner CHAR(50) NOT NULL);

CREATE TABLE file (
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
repo_id INT NOT NULL,
path VARCHAR(200) NOT NULL,
name CHAR(50) NOT NULL);

CREATE TABLE run (
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
repo_id INT NOT NULL,
date DATETIME NOT NULL DEFAULT NOW(),
data JSON CHECK (JSON_VALID(data)),
notes LONGTEXT);

CREATE TABLE run_file (
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
run_id INT NOT NULL,
file_id INT NOT NULL,
data JSON CHECK (JSON_VALID(data)));

ALTER TABLE `file`
  ADD CONSTRAINT `file_repo_id_repo_id`
  FOREIGN KEY (`repo_id`)
  REFERENCES `repo`(`id`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;
ALTER TABLE `run`
  ADD CONSTRAINT `run_repo_id_repo_id`
  FOREIGN KEY (`repo_id`)
  REFERENCES `repo`(`id`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;
ALTER TABLE `run_file`
  ADD CONSTRAINT `run_file_run_id_run_id`
  FOREIGN KEY (`run_id`)
  REFERENCES `run`(`id`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;
ALTER TABLE `run_file`
  ADD CONSTRAINT `run_file_file_id_file_id`
  FOREIGN KEY (`file_id`)
  REFERENCES `file`(`id`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;
